### ISSUE TITLE
Question about how to override template parameter during webpack building

### ISSUE THREAD

**Issue by ranmocy** [StackToolbox/aws-sam-webpack-plugin#78]
I'm trying to conditionally declare entry point based on the different template parameter (dev,beta,prod).
It should affect the output of webpack since the build is based on the entry points declared in the template.

How does the plugin resolve the entry points in the templates? What value will be used for those parameters?

**Comment by buggy** [comment]
The plugin looks for `AWS::Serverless::Function` resources in your SAM template then uses the configured entry point for the function.

**Comment by OscarJVD** [comment]
> The plugin looks for `AWS::Serverless::Function` resources in your SAM template then uses the configured entry point for the function.

And hoy you managed to build correctly when the lambda entry point app.ts has more files and folders at the same level of app.ts. How would be the webpack.config? Because I´ve the problem that only generates the build of app.ts in the correct path but the rest of the files are generated in the root outside of .aws-sam folder. Help
![image](https://github.com/StackToolbox/aws-sam-webpack-plugin/assets/57403552/541d6ca3-fb75-4adc-b954-c949cd5b1510)

**Comment by buggy** [comment]
@ranmocy I'm not going to support conditional logic like this. You could look at the official SAM TypeScript support now it's available of the CDK.
